<a href="https://colab.research.google.com/github/Gizoskos/Pyton-Libraries/blob/main/First.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy nedir?

In [ ]:
# shit enter or f5
##NumPy açık kaynak kodlu ücretsiz ve özgür bir pytohn kütüphanesidir.
#Numerical Python anlamına gelir. Sayılarla daha hızlı mat işlemleri yapmamızı sağlar.
# NumPy kütüphanesinin en temel elemanı arrayleridr.
# Arrayleri Python dizilerinin çok boyutlu olanı gibi düşünebiliriz.
# Arrayler listelerden yaklaşık 50 kat daha hızlı çalışır.
# NumPy arraylerinin hızlı çalışmasının sebebi C ve C++ ile yazılmış olmasıdır.

In [ ]:
# import numpy as np
import numpy as np

NumPy arrayleri oluşturma

In [ ]:
# Arrayler çok boyutlu diziler gibidir.
# 0d (constant), 1d, 2d, 3d, 4d ...

# Arrayleri oluşturmanın 3 farklı yolu vardır.
# 1- Liste ya da tuplee benzeri nesneleri arraye dönüştürebiliriz. np.array([1, 2, 3])
# 2- Built-in hazır fonksiyonlar yardımıyla arrayler oluşturulabilir.  np.arange(), np.linspace(), np.logspace() -Verileri logaritmik artışlarla oluşturur.- vb.
# 3- Rastgele data üreterek.   np.random modülün içindeki fonksiyonlar yardımıyla 

In [ ]:
arr0d = np.array(53) #köşeli parantez sayısı kadar boyut vardır.
arr0d # son ifadeyi print gibi algılar.

array(53)

In [ ]:
arr1d = np.array([1, 2, 3, 4])

In [ ]:
arr2d = np.array([[1,2,3] , [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[100,200,300]]])
arr3d


array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
#Soru : 2d array

In [ ]:
arr2d = np.array([[8,8,7],[2,4,5]])
arr2d

array([[8, 8, 7],
       [2, 4, 5]])

Built-in Functionlarla Hızlıca NumPy Arrayleri oluşturma


In [ ]:
# np.arrange() fonksiyonu ile hızlıca arrayler oluşturulabilir. İstenilen sayı aralığında ardışık artan arrayler oluşurulur.
# range() gibi kullanımı. Start point dahil, End point dahil değil, 
# start stop step parametrelerini alır range() fonsiyonuna benzer şekilde.

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
# np. linspace() fonskiyonuyla da hızlıca arrayler oluşturulabilir. (kaç tane veri döndüreceğini söyleriz) //float

In [ ]:
np.linspace(30,60,6, dtype = int) #endpoint dahil

array([30, 36, 42, 48, 54, 60])

In [ ]:
np.logspace(1,3,10) #üçüncü kaç tane oluşturulacağı 10*1 10*3 arası

array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
         77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
        599.48425032, 1000.        ])

In [ ]:
# Soru : 10,15,20,25....100 şeklindeki arrayi oluşturunuz.

In [ ]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
np.linspace(0,1000,26)

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [ ]:
np.zeros(5, dtype = 'int')

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,3), dtype = int)  # 0 lardan oluşan array

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((3,5), dtype = int) # 3 satır 5 sütun

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones((2,3,5), dtype = int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
np.eye(5, dtype = int) # 5x5 birim matrix


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# Soru : Sadece 0 değerlerinden oluşan (2,6) formatında array oluşturun.

In [ ]:
np.zeros((2,6), dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
# np.random modülünü kullanarak rastgele arrayler oluşturma

In [ ]:
np.random.rand(3) #parametre kaç tane olacağı 0-1 aralığında

array([0.52740935, 0.6804996 , 0.57259993])

In [ ]:
np.random.rand(2,5) #10 tane random değer döndürür.

array([[0.81580195, 0.18816857, 0.96968794, 0.49077547, 0.0777624 ],
       [0.75654431, 0.51515721, 0.07699286, 0.4048732 , 0.61490925]])

In [ ]:
np.random.rand(2,5) * 10  #3 tane 0-10 aralığında değerden oluşan arrayler

array([[1.28288513, 5.72486185, 2.73712195, 9.87883186, 3.09389644],
       [1.92821508, 7.89467967, 5.8670022 , 5.34624958, 8.03695909]])

In [ ]:
np.random.randint(10,50,5) # 10-50 arası 5 tayı

array([35, 10, 21, 46, 48])

In [ ]:
np.random.randint(10,50,(3,6))

array([[19, 15, 40, 15, 20, 24],
       [36, 24, 49, 49, 28, 29],
       [19, 36, 35, 39, 27, 48]])

In [ ]:
# Soru : 0-50 arasında rastgele sayılardan oluşan 4-6 formatında 24 tane sayıdan oluşan bir array oluşturun.

In [ ]:
np.random.randint(10,50,(4,6))

array([[27, 11, 29, 41, 46, 11],
       [40, 46, 31, 23, 34, 20],
       [16, 46, 34, 31, 24, 40],
       [36, 19, 16, 10, 31, 14]])

Arrayin Boyut Sayısını ve Shape'ini Kontrol Etmek

In [ ]:
arr0d

NameError: ignored

In [ ]:
arr1d

array([1, 2, 3, 4])

In [ ]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
arr1d.ndim

1

In [ ]:
arr3d.ndim

3

In [ ]:
#.shape attribute ' ı ile arrayin shapeine bakılabilir.

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
arr3d.shape # 2 blok sayısı 2 bloktaki satırlar 3 sütun

(2, 2, 3)

NumPy Arraylerini İndeksleme ve Öğelerine Erişme

In [ ]:
arr1d #Bir boyutlu arrayler listeler gibidir.

array([1, 2, 3, 4])

In [ ]:
arr1d[0]

1

In [ ]:
arr2d

array([[8, 8, 7],
       [2, 4, 5]])

In [ ]:
arr2d[0]

array([8, 8, 7])

In [ ]:
arr2d[0][1]

8

In [ ]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
arr3d[0][1][2]

6

In [ ]:
arr3d[1][0][-1] #negatif indeksleme

9

In [ ]:
# Soru : 53'den 61'e kadar(53 ve 61 dahil) olan tam sayıları içeren bir array oluşturun. Ardından bu array'in 4.indexindeki sayıyı ekrana bastırın.

In [ ]:
arr = np.arange(53,62)
arr

array([53, 54, 55, 56, 57, 58, 59, 60, 61])

In [ ]:
arr[4]

57

In [ ]:
arr = np.arange(53,62)[4]
arr


57

In [ ]:
arr

57

# NumPy Dizilerinin Max- Min Elemanlarına ve bu elemanların indexlerine erişme

In [ ]:
arr = np.random.randint(1,100,10)
arr

array([34, 79, 42, 23, 79, 99, 42, 41, 65, 22])

In [ ]:
arr.max()

99

In [ ]:
arr.argmax() # max değerin indexi

5

In [ ]:
arr.min()

22

In [ ]:
arr.argmin() 

9

# NumPy arraylerinde Slicing(Dilimleme) yapılabilir.

In [ ]:
arr = np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [ ]:
arr[5:11] # 10 dahil şu an

array([55, 56, 57, 58, 59, 60])

In [ ]:
arr[-5:] #sonuna kadar git

array([60, 61, 62, 63, 64])

In [ ]:
arr[2:10:2] # ikişer ikişer gider

array([52, 54, 56, 58])

In [ ]:
arr[5:11] = 999 #Broadcasting 5-11 arasındaki tüm değerleri 999 a eşitler.

In [ ]:
arr

array([ 50,  51,  52,  53,  54, 999, 999, 999, 999, 999, 999,  61,  62,
        63,  64])

In [ ]:
# -30 ile 10(İkisi de dahil) arasındaki tam sayılardan bir array oluşturun. Ardından slicing yaparak 5. ve 18. indexler arasındaki sayılardan(ikisi de dahil) oluşan bir array oluşturun.

In [ ]:
arr1 = np.arange(-30,11)

In [ ]:
arr1

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10])

In [ ]:
arr1[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

# Bir Arrayin Veri Türünü (Data Type'ını) Kontrol Etme

In [ ]:
#.dtype attribute'ı ile arrayin data type'ı kontrol edilelbilir.

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr2 = np.arange(100, dtype = 'float')
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [ ]:
arr2.dtype


dtype('float64')

In [ ]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
arr3.dtype

dtype('<U1')

# Bir Arrayin Dtype ını Değiştirme

In [ ]:
arr = np.array([1.2, 3.5, 5.8])
arr

array([1.2, 3.5, 5.8])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
# .astype() methodu ile arraylerin dtype ı değiştirilebilir.

In [ ]:
arr.astype('int')


array([1, 3, 5])

In [ ]:
# Soru :
# arr = np.array(['5', '7', '19', '1', '22', '99', '4']) şeklindeki array'in type'ını int'e döndürün ardından dtype'ını kontrol edin.

In [ ]:
arr = np.array(['5', '7', '19', '1', '22', '99', '4'])
arr1 = arr.astype('int')
arr1.dtype

dtype('int64')